stages:
  - build
  - test

build:
  stage: build
  image: maven:3.9-eclipse-temurin-21
  script:
    - mvn clean compile -q
  rules:
    - if: $CI_COMMIT_BRANCH

test:
  stage: test
  image: maven:3.9-eclipse-temurin-21
  script:
    - mvn clean test -q
  rules:
    - if: $CI_COMMIT_BRANCH
